server:
  port: 3001

spring:
  application:
    name: course
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/ead_course
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
